// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWaguB1SFc3qFaf2gsLjcrT5H2TOzaId8',
    appId: '1:483341389734:web:38d6eefc4513546ad50967',
    messagingSenderId: '483341389734',
    projectId: 'clinic-management-cc484',
    authDomain: 'clinic-management-cc484.firebaseapp.com',
    storageBucket: 'clinic-management-cc484.firebasestorage.app',
    measurementId: 'G-47R800QJPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcK_nNqU7cOmBlyWFijKw_0l8gyH5PA40',
    appId: '1:483341389734:android:e183337d1ec01718d50967',
    messagingSenderId: '483341389734',
    projectId: 'clinic-management-cc484',
    storageBucket: 'clinic-management-cc484.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbqlInByb2ahpt8icJwoTVnyvtnU7hOYg',
    appId: '1:483341389734:ios:8e98a1414b408e2cd50967',
    messagingSenderId: '483341389734',
    projectId: 'clinic-management-cc484',
    storageBucket: 'clinic-management-cc484.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagemnet',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqlInByb2ahpt8icJwoTVnyvtnU7hOYg',
    appId: '1:483341389734:ios:8e98a1414b408e2cd50967',
    messagingSenderId: '483341389734',
    projectId: 'clinic-management-cc484',
    storageBucket: 'clinic-management-cc484.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagemnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWaguB1SFc3qFaf2gsLjcrT5H2TOzaId8',
    appId: '1:483341389734:web:38d6eefc4513546ad50967',
    messagingSenderId: '483341389734',
    projectId: 'clinic-management-cc484',
    authDomain: 'clinic-management-cc484.firebaseapp.com',
    storageBucket: 'clinic-management-cc484.firebasestorage.app',
    measurementId: 'G-47R800QJPL',
  );
}
